name: Bot Weeek

on:
  push:
    branches:
      - main # Указывает на ветку, изменения в которой будут инициировать процесс деплоя

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Execute deployment commands
        run: |
          ssh -o StrictHostKeyChecking=no levpavloff@185.185.70.149 'cd /var/www/projects/bot && git pull origin main'